### ISSUE TITLE
Example doesn't start chromium with puppeteer in docker

### ISSUE THREAD

**Issue by Industrial** [actionsflow/actionsflow#29]
## Description

Chromium isn't starting in the docker container.

### Steps to reproduce

Add https://github.com/actionsflow/actionsflow/blob/main/examples/actionsflow-workflow-example/workflows/reddit-combine.yml to workflows and run.

### Expected result

Outpout as in the example.

### Actual result
/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
    at Interface.<anonymous> (/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:68)
    at Interface.emit (events.js:388:22)
    at Interface.close (readline.js:429:8)
    at Socket.onend (readline.js:202:10)
    at Socket.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
UNHANDLED REJECTION TriggersError: Multiple Errors when running triggers
    at build (/usr/local/lib/node_modules/actionsflow/dist/src/build.js:242:15)
    at async runWorkflows (/usr/local/lib/node_modules/actionsflow/dist/src/run-workflows.js:18:5)
    at async /usr/local/lib/node_modules/actionsflow/dist/src/cron.js:13:13 {
  errors: [
    {
      error: Error: Failed to launch the browser process!
      /usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/.local-chromium/linux-901912/chrome-linux/chrome: error while loading shared libraries: libgobject-2.0.so.0: cannot open shared object file: No such file or directory

      TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

          at onClose (/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:203:20)
          at Interface.<anonymous> (/usr/local/lib/node_modules/actionsflow/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:193:68)
          at Interface.emit (events.js:388:22)
          at Interface.close (readline.js:429:8)
          at Socket.onend (readline.js:202:10)
          at Socket.emit (events.js:388:22)
          at endReadableNT (internal/streams/readable.js:1336:12)
          at processTicksAndRejections (internal/process/task_queues.js:82:21),
      trigger: [Object],
      workflow: [Object]
    }
  ]
}

**Comment by theowenyoung** [comment]
Hi, @Industrial ,Thanks for the report!

I've updated the doc of Reddit when using `puppeteer-fetch` as the client, see it [here](https://github.com/actionsflow/actionsflow/blob/main/packages/actionsflow-trigger-reddit/README.md#options)

> Note: if you use puppeteer-fetch as the client, then you must use using: local arguments to run workflows, because actionsflow/actionsflow-action can not load puppeteer in action. We must use normal local node_modules to run it.

```yml
jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    concurrency: actionsflow
    steps:
      - uses: actions/checkout@v2
      - name: Run Actionsflow
        uses: actionsflow/actionsflow-action@v1
        with:
          using: local
```

**Comment by Industrial** [comment]
Hi @theowenyoung, thanks for your quick reply.

I've added the `using: local` to the `actionsflow.yml` here: https://github.com/Industrial/configuration-actionsflow/blob/main/.github/workflows/actionsflow.yml#L36

But I get the same output. Did I do it right?

**Comment by theowenyoung** [comment]
oh, now it's a different error, it seems that act can not find the output JSON.

Let me inspect it now.

I'll fork your repo.

**Comment by theowenyoung** [comment]
@Industrial  https://github.com/Industrial/configuration-actionsflow/pull/1

**Comment by Industrial** [comment]
Hi @theowenyoung,

following the PR above I've installed the NPM dependencies (I thought this wasn't needed when running inside a docker container).

When I run `npm run start` I get this:

```
> actionsflow-workflow-default@1.0.0 start
> actionsflow start

Actionsflow CLI version: 1.12.0

[01:46:42] INFO actionsflow: Start server at http://localhost:3000
[01:46:42] INFO actionsflow: Listen webhook endpoint at http://localhost:3000/webhook/
[01:46:42] INFO actionsflow: Start cron tasks
[01:46:42] INFO actionsflow: Clean the dest folder dist/.cron/1640656002661
[01:46:42] INFO actionsflow: There are 3 immediate tasks, 0 delay tasks
[01:46:46] INFO actionsflow: Run 3 immediate tasks finished, wait for 0 delay tasks to finish...
[01:46:46] INFO actionsflow: All tasks finished, wait for building...
[01:46:46] INFO actionsflow: 25 updates found at trigger [reddit] of workflow [reddit-news.yml], workflow file 0-reddit-news-reddit.yml build success
[01:46:46] INFO actionsflow: 25 updates found at trigger [reddit] of workflow [reddit-stocks.yml], workflow file 1-reddit-stocks-reddit.yml build success
[01:46:46] INFO actionsflow: 10 updates found at trigger [rss] of workflow [rss.yml], workflow file 2-rss-rss.yml build success
[01:46:46] INFO actionsflow: Done.
[0-reddit-news-reddit.yml/Send a message to discord 0 ] 🚀  Start image=actionsflow/act-environment:v1
[0-reddit-news-reddit.yml/Send a message to discord 0 ]   🐳  docker pull image=actionsflow/act-environment:v1 platform= username= forcePull=false
[0-reddit-news-reddit.yml/Send a message to discord 0 ]   🐳  docker create image=actionsflow/act-environment:v1 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[0-reddit-news-reddit.yml/Send a message to discord 0 ]   🐳  docker run image=actionsflow/act-environment:v1 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[0-reddit-news-reddit.yml/Send a message to discord 0 ]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
[0-reddit-news-reddit.yml/Send a message to discord 0 ] ⭐  Run Discord notification
INFO[0004]   ☁  git clone 'https://github.com/Ilshidur/action-discord' # ref=master
[0-reddit-news-reddit.yml/Send a message to discord 0 ]   🐳  docker pull image=act-ilshidur-action-discord-master-dockeraction:latest platform= username= forcePull=false
[0-reddit-news-reddit.yml/Send a message to discord 0 ]   🐳  docker create image=act-ilshidur-action-discord-master-dockeraction:latest platform= entrypoint=[] cmd=["${{" "(fromJSON(env.ACTIONSFLOW_TRIGGER_RESULT_FOR_reddit)).outputs.title" "}}" "${{" "(fromJSON(env.ACTIONSFLOW_TRIGGER_RESULT_FOR_reddit)).outputs.link" "}}"]
[0-reddit-news-reddit.yml/Send a message to discord 0 ]   🐳  docker run image=act-ilshidur-action-discord-master-dockeraction:latest platform= entrypoint=[] cmd=["${{" "(fromJSON(env.ACTIONSFLOW_TRIGGER_RESULT_FOR_reddit)).outputs.title" "}}" "${{" "(fromJSON(env.ACTIONSFLOW_TRIGGER_RESULT_FOR_reddit)).outputs.link" "}}"]
| lodash.templateSources[0]:6
| __p += '$' +
| ^
|
| ReferenceError: fromJSON is not defined
|     at eval (lodash.templateSources[0]:6:1)
|     at Object.<anonymous> (/entrypoint.js:41:35)
|     at Module._compile (internal/modules/cjs/loader.js:1015:30)
|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
|     at Module.load (internal/modules/cjs/loader.js:879:32)
|     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
|     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
|     at internal/main/run_main_module.js:17:47
[0-reddit-news-reddit.yml/Send a message to discord 0 ]   ❌  Failure - Discord notification
Error: exit with `FAILURE`: 1
UNHANDLED REJECTION Error: Shell command exit with non zero code: 1
    at ChildProcess.<anonymous> (/home/tom/Code/configuration/configuration-actionsflow/node_modules/exec-sh/lib/exec-sh.js:73:15)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  code: 1,
  stdout: '',
  stderr: ''
}
```

**Comment by theowenyoung** [comment]
If you use the example rss.yml, you should set `secrets.DISCORD_WEBHOOK_NEWS` locally.

Create `.secrets`, with:

```bash
DISCORD_WEBHOOK_NEWS=xxxxx
```

https://github.com/Industrial/configuration-actionsflow/blob/ae416695c350222a050e4399de6d80ba8c42535c/workflows/rss.yml#L26


I don't know if this is fixed, it can work well, if any further problem, please leave a comment.

**Comment by theowenyoung** [comment]
And, Actually, you should install npm dependences locally, because only `act` will run in docker, `actionsflow` will run in the local node enviroment.

**Comment by Industrial** [comment]
@theowenyoung, I have a `.secrets` file already with the webhook in there. The error that it shows is not about the webhook or the secret.

```
> actionsflow-workflow-default@1.0.0 start
> actionsflow start

Actionsflow CLI version: 1.12.0

[02:15:49] INFO actionsflow: Start server at http://localhost:3000
[02:15:49] INFO actionsflow: Listen webhook endpoint at http://localhost:3000/webhook/
[02:15:49] INFO actionsflow: Start cron tasks
[02:15:49] INFO actionsflow: Clean the dest folder dist/.cron/1640657749303
[02:15:49] INFO actionsflow: There are 1 immediate tasks, 0 delay tasks
[02:15:50] INFO actionsflow: Run 1 immediate tasks finished, wait for 0 delay tasks to finish...
[02:15:50] INFO actionsflow: All tasks finished, wait for building...
[02:15:50] INFO actionsflow: 10 updates found at trigger [rss] of workflow [rss.yml], workflow file 0-rss-rss.yml build success
[02:15:50] INFO actionsflow: Done.
[0-rss-rss.yml/Send a message to discord 0] 🚀  Start image=actionsflow/act-environment:v1
[0-rss-rss.yml/Send a message to discord 0]   🐳  docker pull image=actionsflow/act-environment:v1 platform= username= forcePull=false
[0-rss-rss.yml/Send a message to discord 0]   🐳  docker create image=actionsflow/act-environment:v1 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[0-rss-rss.yml/Send a message to discord 0]   🐳  docker run image=actionsflow/act-environment:v1 platform= entrypoint=["/usr/bin/tail" "-f" "/dev/null"] cmd=[]
[0-rss-rss.yml/Send a message to discord 0]   🐳  docker exec cmd=[mkdir -m 0777 -p /var/run/act] user=root workdir=
[0-rss-rss.yml/Send a message to discord 0] ⭐  Run Discord notification
INFO[0001]   ☁  git clone 'https://github.com/Ilshidur/action-discord' # ref=master
[0-rss-rss.yml/Send a message to discord 0]   🐳  docker pull image=act-ilshidur-action-discord-master-dockeraction:latest platform= username= forcePull=false
[0-rss-rss.yml/Send a message to discord 0]   🐳  docker create image=act-ilshidur-action-discord-master-dockeraction:latest platform= entrypoint=[] cmd=["${{" "(fromJSON(env.ACTIONSFLOW_TRIGGER_RESULT_FOR_rss)).outputs.title" "}}" "${{" "(fromJSON(env.ACTIONSFLOW_TRIGGER_RESULT_FOR_rss)).outputs.link" "}}"]
[0-rss-rss.yml/Send a message to discord 0]   🐳  docker run image=act-ilshidur-action-discord-master-dockeraction:latest platform= entrypoint=[] cmd=["${{" "(fromJSON(env.ACTIONSFLOW_TRIGGER_RESULT_FOR_rss)).outputs.title" "}}" "${{" "(fromJSON(env.ACTIONSFLOW_TRIGGER_RESULT_FOR_rss)).outputs.link" "}}"]
| lodash.templateSources[0]:6
| __p += '$' +
| ^
|
| ReferenceError: fromJSON is not defined
|     at eval (lodash.templateSources[0]:6:1)
|     at Object.<anonymous> (/entrypoint.js:41:35)
|     at Module._compile (internal/modules/cjs/loader.js:1015:30)
|     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
|     at Module.load (internal/modules/cjs/loader.js:879:32)
|     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
|     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
|     at internal/main/run_main_module.js:17:47
[0-rss-rss.yml/Send a message to discord 0]   ❌  Failure - Discord notification
Error: exit with `FAILURE`: 1
UNHANDLED REJECTION Error: Shell command exit with non zero code: 1
    at ChildProcess.<anonymous> (/home/tom/Code/configuration/configuration-actionsflow/node_modules/exec-sh/lib/exec-sh.js:73:15)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1055:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  code: 1,
  stdout: '',
  stderr: ''
}
^C[02:16:00] INFO actionsflow:
Stopping actionflow...
```

It looks like it can't find the `fromJSON()` function.

**Comment by theowenyoung** [comment]
Can you give the workflow file with this error? I'll test it locally.

**Comment by theowenyoung** [comment]
I just test with the following yml locally, it seems doesn't work,

I think it maybe break with [act](https://github.com/nektos/act) or discord action?

```yml
'on':
  - push
jobs:
  discord_0:
    name: Send a message to discord 1
    runs-on: ubuntu-latest
    steps:
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: '${{ secrets.DISCORD_WEBHOOK_NEWS }}'
        uses: Ilshidur/action-discord@master
        with:
          args: 'test111'
   
```

**Comment by theowenyoung** [comment]
It's ok at github https://github.com/theowenyoung/test-actions/actions/runs/1629029606

**Comment by theowenyoung** [comment]
Ignore the above message, actually the simple file works fine in the locally, I'll do more inspect.

**Comment by theowenyoung** [comment]
https://github.com/theowenyoung/test-actions/blob/master/.github/workflows/discord.yml

Actually, this dist yml works fine with github native action, so it's maybe an act issue...

**Comment by theowenyoung** [comment]
Just submit a pr:  https://github.com/Industrial/configuration-actionsflow/pull/3

this works fine on my computer locally.

**Comment by Industrial** [comment]
I got it working as well. Thanks for the help :)

I added several flows for RSS and Reddit, aggregating news that I'm interested in :-)

**Comment by theowenyoung** [comment]
Have fun!
